name: Deploy Frontend to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repo
        uses: actions/checkout@v3

      - name: Iniciar sesión en DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Construir imagen
        run: docker build -t ${{ secrets.DOCKER_USER }}/artworks-mysql-frontend .

      - name: Subir imagen
        run: docker push ${{ secrets.DOCKER_USER }}/artworks-mysql-frontend
